= Field Day Registration Kiosk

== Why

I am learning Go by migrating my Field Day registration application that 
I wrote several years ago to learn Django.

I am using Jon Calhoun's course (https://www.usegolang.com/) for that slightly
modifying it for my own needs and updating some components (like Bootstrap from 3 to 5 and gorm.io).

Of course, the course and the project have more than I need for this simple app, but -- I am learning. :-) 

== Deployment

(Mostly these notes are for myself to be able to reproduce the setup next year
without much googling.)

I put the app on a Raspberry Pi. In my case it was Raspberry Pi 2 Model B (even without wireless) 
so I didn't worry about leaving it at the registration table in the park where we had
our Field Day.

I created a simple Makefile to build and copy the application into the appropriate 
directories.
It creates a service that starts the app automatically when the system boots.

I created a user named `registration` on the RPi and in that user's Chromium browser I set the start page
to `http://localhost:3000/new`.

I followed the instructions from here: https://smarthomepursuits.com/disable-sleep-on-raspberry-pi/
to disable screen lock and autostart Chromium in full screen mode.

I followed the instructions from here: https://raspberrypi.stackexchange.com/questions/40415/how-to-enable-auto-login
to enable autologin for the user that will access the app.

== Hardware

I use Raspberri Pi to run this at the Field Day location. 
Since I added the registration timestamps I noticed gaps in the registration.
Apparently that was because somebody turned off the system during the night and 
Raspberry Pi lost the date.
When I connect it to Internet (via a hotspot on my phone) it restores the date,
but some registration timestamps are still shifted.

I am going to add an RTC (real-time clock) to the Pi to keep the date even when it's powered off.
This might be a good source of information: https://pimylifeup.com/raspberry-pi-rtc/.


== Post-event processing

Use the following instructions to convert the visitors data to CSV: https://www.sqlitetutorial.net/sqlite-export-csv/

 


