= Field Day Registration Kiosk

== Why

I am learning Go by migrating my Field Day registration application that 
I wrote several years ago to learn Django.

I am using Jon Calhoun's course (https://www.usegolang.com/) for that slightly
modifying it for my own needs and updating some components (like Bootstrap from 3 to 5 and gorm.io).

Of course, the course and the project have more than I need for this simple app, but -- I am learning. :-) 

== Deployment

(Mostly these notes are for myself to be able to reproduce the setup next year
without much googling.)

I put the app on a Raspberry Pi. In my case it was Raspberry Pi 2 Model B (even without wireless) 
so I didn't worry about leaving it at the registration table in the park where we had
our Field Day.

I created a simple Makefile to build and copy the application into the appropriate 
directories.
It creates a service that starts the app automatically when the system boots.

I created a user named `registration` on the RPi and in that user's Chromium browser I set the start page
to `http://localhost:3000/new`.

I followed the instructions from here: https://smarthomepursuits.com/disable-sleep-on-raspberry-pi/
to disable screen lock and autostart Chromium in full screen mode.

I followed the instructions from here: https://raspberrypi.stackexchange.com/questions/40415/how-to-enable-auto-login
to enable autologin for the user that will access the app.

 


