= Field Day Registration Kiosk

I wrote this simple program to help my Amateur Radio club (North Fulton Amateur Radio League)
to register visitors on our annual Field Day event.

Over the years it became my sandbox to try and practice various ideas and development approaches.

== Deployment

The application is usually deployed on a Raspberry Pi.
It can deployed on any other computer that you can leave in the park overnight.

=== Prerequisites

* Linux OS (any recent version will do)
* Go 1.18 and higher
* Git CLI
* gcc (see here: https://github.com/mattn/go-sqlite3#installation)
* `sudo` access on the target host

=== Build

. Clone this repo on the target computer and `cd` into that directory.
. Run `make build`. That will create a binary in the root directory.
. Test it by running `./fieldday test.db`. Enter one or two visitors.
Check if they were added to the database by adding `/list` to the main URL (instead of `/new`).

=== Install

. Run `sudo make install`. That will copy the binary and template files to `/var/local/fieldday`.
. Run `sudo make user`. That will create a user named `nfarl` and configure their environment (e.g. autostart of the browser in full screen mode, etc.).

=== Upgrade

. `git pull`
. `make build`
. `sudo make install`

=== Real-time clock

The program adds timestamps to each visitor record automatically.
But in the field the host doesn't have any network connection so in case somebody turns it off the timestamps will be all wrong after that.
To avoid such a situation you can add a simple battery-powered real-time clock (RTC) to Raspberry Pi and configure it accordingly.

This is the one I added to my installation: https://www.amazon.com/Makerfire%C2%AE-Raspberry-Module-DS1307-Battery/dp/B00ZOXWHK4/

This is a good instruction on how to configure it: https://pimylifeup.com/raspberry-pi-rtc/.

== Post-event processing

Use the following instructions to convert the visitors data to CSV: https://www.sqlitetutorial.net/sqlite-export-csv/




